schmunk42/yii2-giiant

model/Generator.php, model/default/model.php
=> Added ns to @property to use with autocomplete on IDE - #40

README.md, crud/providers/OptsProvider.php
https://github.com/schmunk42/yii2-giiant/pull/46
=> Added dropdown "prompt" description

crud/default/views/_form.php
Here there may be a more appropriate treatment. Think about it later ....
=> Check if column exists

commands/BatchController.php
Otherwise I can't easily extend the other modes/crud actions
=> make $appConfig protected

crud/providers/RelationProvider.php
=> add new line after action column

crud/providers/RelationProvider.php
=> fix spacing

commands/BatchController.php
batch generator should have options for ActiveQuery class
=> more changes relating to #65

commands/BatchController.php, model/Generator.php
When running batch model generator, all tables will be used if none is specified.
=> Console BatchController will be run for all tables by default

commands/BatchController.php, crud/Generator.php, crud/form.php, model/Generator.php, model/form.php
e.g. ./yii giiant-batch --tables=cms_Persons --singularEntities=1 --tablePrefix=cms_
... would generate classes Person, PersonQuery, PersonController etc.
=> Add option for converting entity names to singular form

model/Generator.php, model/default/model.php, model/form.php
Implements some of the features discussed in issue #4
=> Added option to use 2amigos/yii2-translateable-behavior in model generator

commands/BatchController.php, model/Generator.php
This seems to be the way the default Gii is doing it.
What are your thoughts on this?
=> Use XxxSearch instead of Xxx as search model

src/helpers/SaveForm.php
Also add `gii` directory in the `@common` alias, if that directory exists, to look for saved forms.
=> Add @common/gii

src/generators/crud/Generator.php, src/generators/crud/form.php
Signed-off-by: Garth Murray <garthpmurray@gmail.com>
=>  Generate Access Filter Migrations #179

src/generators/crud/Generator.php, src/generators/crud/ProviderTrait.php, src/generators/crud/default/views/_form.php, src/generators/crud/default/views/create.php, src/generators/crud/default/views/index.php, src/generators/crud/default/views/update.php, src/generators/crud/default/views/view.php, src/generators/crud/providers/core/RelationProvider.php
i'd like to set tidy-output by default to make the generated code more readable.
=> enabling tidyOutput by default

src/generators/model/Generator.php
Apply custom model name in UI version of Giiant
https://github.com/schmunk42/yii2-giiant/issues/176
=> Apply cutom model name in UI giiant

CHANGELOG.md, src/generators/crud/callbacks/yii/Db.php
=> improved detection of text columns

src/generators/crud/default/views/view.php
another small relation fix to get also has_one related model tabs in model view
=> get has_one relations as tab in model view

src/generators/model/default/model-extended.php
Added four spaces to line 30, to correctly indent  the function.
On the rules function, correctly indented all to 4 spaces.
=> Fixed spacing in model extended template.

src/commands/BatchController.php
Skip db tables for generating models
=> update for skip db tables

src/generators/model/Generator.php
Hi @schmunk42 
I found one bug of the setting singularEntities is not working after your last update. :)
=> Fix singularEntities not working when using cli

src/helpers/SaveForm.php
Added additional validation for module class existence
=> Additional validation

src/commands/BatchController.php
Added missing option to the BatchController which is already described in the [docs.](https://github.com/schmunk42/yii2-giiant/blob/master/docs/25-cli-commands.md)
=> Added generateAccessFilterMigrations option for CLI

CHANGELOG.md, docs/20-batches.md, src/commands/BatchController.php, src/generators/crud/Generator.php, src/generators/crud/default/views/index.php, src/generators/crud/providers/core/RelationProvider.php, tests/acceptance/onlyCrud/CrudCept.php, tests/acceptance/sakila/CrudCept.php
- dropdown list in GridView filed search filter optimization
- select position ActionColumn in GridView (left or right)
- fix view icon in ActionColumn
- pager align in GridView
=> Some fix and improvements

src/generators/model/Generator.php, src/generators/model/default/model.php
=> Fix ENUM labels

src/commands/BatchController.php, src/generators/model/Generator.php, src/generators/model/default/model.php
Add `timestampBehaviorClass` config to support use custom behavior class for timestamp.
=> Support custome TimestampBehavior

CHANGELOG.md, composer.json, docs/25-cli-commands.md, src/commands/BatchController.php, src/generators/model/Generator.php, src/generators/model/form.php
Version 2.2.0 of yii2-gii supports `modelGenerateJunctionRelationMode`. This PR brings the new feature to Giiant.
=> Support for modelGenerateJunctionRelationMode

src/commands/BatchController.php
=> Allow configuration of ModelGenerator in BatchController

CHANGELOG.md, composer.json
See https://github.com/schmunk42/yii2-giiant/pull/281#issuecomment-969056475
=> Updated php-cs-fixer to version 3

src/generators/model/default/model.php
E.g. for filter trim or something similar
=> Merge parent rules to allow apply base rules

src/generators/model/default/model.php, src/generators/module/default/controller.php, src/generators/module/default/view.php, src/generators/module/form.php
Move business logic from view to controller
=> cleanup giiant module generator code files

src/generators/crud/callbacks/yii/Html.php
=> fixed html_entity_decode(): Passing null to parameter #1 ($string) of type string is deprecated
