crud/providers/DateTimeProvider.php
for ease of development, so we don't have to look it up
=> added format

src/generators/model/Generator.php, src/generators/model/default/model.php, src/generators/model/form.php
Add feature to automatically generate code for yii2 core `TimestampBehavior` and `Blameablebehavior`. Rules for the fields that are used by these behaviors are not generated. Column names other than the default `created_at`, `updated_at`, `created_by`, `updated_at` can be used.
=> Add TimestampBehavior and BlameableBehavior to model generator

src/generators/model/Generator.php, src/generators/model/default/model.php
I have rewritten the `generateHints` method, which was originally copied from the `generateLabels` method.
* The Generator's `generateHints` method now no longer generates attribute hints from column names  (it previously did when there wasn't a column comment). This seems more appropriate to me as by default the labels' text is also generated from column names.
* Setting 'Generate Hints from DB Comments' check-box off now results in hints not being generated.
* Also fixes some inconsistent indentation I introduced in #140.
=> Improve attribute hints generation

src/generators/crud/default/controller-extended.php
Produced following code when using yii 2.0.6 advanced template
namespace backend\controllers;
[...]
class UserController extends \\base\UserController
Fix respect's theses circumstance:
namespace backend\controllers;
class UserController extends base\UserController
=> Corrected Ns-Handling in Template

src/generators/crud/form.php
In your form view https://github.com/schmunk42/yii2-giiant/blob/master/src/generators/crud/default/views/_form.php :27 you use yii\bootstrap\ActiveForm, which support only 3 kind of layout: ['default', 'horizontal', 'inline'].
Then if we chek vertical layout - we get error:
yii\base\InvalidConfigException: Invalid layout type: vertical in /home/mix/www/chaos/vendor/yiisoft/yii2-bootstrap/ActiveForm.php:92
=> default layout name fix in form.php

src/generators/crud/default/views/index.php
because the font family of i tag is glyphicon, put words in <i> tag will make the word look ugly
=> words should be put outside of <i> tag

src/commands/BatchController.php
Without leading slash, CRUD urls to relations will result in routes like `crud/crud/question/index`, which is wrong. example configs also specify the / prefix on the route, e.g.:
https://github.com/schmunk42/yii2-giiant/blob/b20f277ff994cd5cb49fcd15172cea5ba6aac769/docs/example-config.php#L47
=> Fix broken URLs on crud relations

docs/31-callback-provider-examples.md
`$attribute` is a string in some of the places I have tried. I replaced all occurences here, not sure if its correct to apply in all cases.
=> Fix CallbackProvider examples

src/generators/crud/ModelTrait.php
if no types to filter are given to ModelTrait::getModelRelations we should return all types.
Otherwise giiant will generate empty relation selects e.g. in generators/crud/default/views/index.php
=> fixed ModelTrait::getModelRelations if no types are given

src/commands/BatchController.php, src/generators/model/default/model.php
Current BatchController can not be used to set `createdAtColumn` and `updatedAtColumn` for `useTimestampBehavior`, as well as `createdByColumn` and `updatedByColumn` for `useBlameableBehavior`.
I just simply add those properties from `schmunk42\giiant\generators\model\Generator` into `schmunk42\giiant\commands\BatchController`
=> include basic attributes from model generator into BatchController

src/generators/crud/providers/core/RelationProvider.php
When using the relation getter to access a model's relations, a db query is executed even if the relation has already been loaded to the model.
Switch to using the relation property, which will make the db query if the relation has not been retrieved yet, else it will simply use the previously retrieved relation data.
=> use relation property instead of relation getter

src/commands/BatchController.php
Each new app instance will open a new database connection, when generating a lot of models this causes a "Too many connections" error.
This PR closes the database of the temp app before unloading it (which does not automatically closes the db connection).
=> Close DB after each model generation

src/generators/crud/default/views/create.php, src/generators/crud/default/views/update.php, src/generators/crud/default/views/view.php
Added Html::encode in CRUD views default templates to fixing XSS Vulnerability when using string in primary key.
XSS Attack
Fixed
=> Fix XSS Vulnerability in CRUD views generated

src/generators/crud/default/views/index.php
The "View" action button in default crud index template had static 'crud' message category.
=> Correct message category for view action button

src/generators/crud/ModelTrait.php
PHP Warning 'yii\base\ErrorException' with message '"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?'
=> error with php 7.3

composer.json
fix error:
```
Problem 1
- Can only install one of: yiisoft/yii2-gii[2.0.x-dev, 2.1.0].
- Can only install one of: yiisoft/yii2-gii[2.0.x-dev, 2.1.0].
- schmunk42/yii2-giiant dev-master requires yiisoft/yii2-gii ~2.0.6 -> satisfiable by yiisoft/yii2-gii[2.0.x-dev].
- Installation request for schmunk42/yii2-giiant dev-master -> satisfiable by schmunk42/yii2-giiant[dev-master].
- Installation request for yiisoft/yii2-gii ~2.1.0 -> satisfiable by yiisoft/yii2-gii[2.1.0].
```
=> update composer.json for yii-gii new version and newer version

src/generators/model/Generator.php, src/helpers/SaveForm.php
When using `table*` model generation the generated json files kept the `*` in the table name instead of their respective table name (if this was just one json file saving the multi-table format this would of been fine). I've went in and fixed the generation model's tablename and class while it's creating the JSON file data so that each JSON file created has the proper variables now to be re-used. I've also fixed the labels for the dropdown so they actually say the correct module/path that they are stored in, before it was just using the last value from a for each loop.
=> Fixed multi-table model json generation

src/commands/BatchController.php
If prefix and map are defined together, you had to define the TableNames in the map once with and once without prefix.
This PR makes creation of the class name between model and crud generator more consistent so that the definition in the map is only necessary once (with prefix)
=> make creation of the class name between model and crud generator consistent

src/commands/BatchController.php
The crud generator has properties to overwrite generated class files:
- overwriteSearchModelClass
- overwriteRestControllerClass
- overwriteControllerClass
This PR adds these crud generator options to the BatchController prefixed with `crud`
- crudOverwriteSearchModelClass
- crudOverwriteRestControllerClass
- crudOverwriteControllerClass
Default values are `false` as in crud generator.
=> added overwrite*Class options from crud generator to BatchController

src/generators/model/default/model.php
> Note: The PHP 4 method of declaring a variable with the var keyword is still supported for compatibility reasons (as a synonym for the public keyword). In PHP 5 before 5.1.3, its usage would generate an E_STRICT warning.
https://www.php.net/manual/en/language.oop5.visibility.php
=> Removed deprecated code and not needed

CHANGELOG.md, docs/25-cli-commands.md, src/commands/BatchController.php, src/generators/model/Generator.php
When generating models for many tables (and relations) the generation can take quite some time.
The majority of the time is spent on the `generateRelations` function. Since this function returns the same data for each table this data can be cached.
Test data: 224 tables
| cacheRelationsData  | Duration |
| ------------- | ------------- |
| false  | 1:00:30  |
| true  | 0:01:12  |
In this case the models were generated more than 50x faster with caching enabled.
As far as I can see it is fully backwards compatible. But I've added the `modelCacheRelationsData` option to disable the cache just in case.
=> Improved model generation performance

src/generators/crud/default/views/view.php
If model has not default name attribute (not 'name', or 'title') (see yii2-gii yii\gii\generators\crud\Generator:221)- in breadcrumps will be used its ID attribute instead of getLabel() method (see yii2-giiant\src\generators\crud\default\views\view.php 
By the way in a header of view's page use getLabel() method
So I changed $generator->getNameAttribute() (gii module method) with $generator->genModelNameAttribute() (giiant crud RelationTrait method)
After changing generation looks like
As you can see generator started using getLabel() method of model to get main name attribute
=> Fix getting name attribute on cruds/view

src/helpers/SaveForm.php
Error in PHP 8.1 method_exists(): Argument #1 ($object_or_class) must be of type object|string, array given
=> PHP 8.1 compatibility

src/commands/BatchController.php
Currently the Application class is fixed in the BatchController. When a custom Application is used the configuration might not compatible with the default `yii\console\Application`.
This PR allows configuration of the Application class so that a custom class can be specified.
=> Allow configuration of the Application class

src/commands/BatchController.php
The `$params` contains a duplicate array key 'template':
https://github.com/schmunk42/yii2-giiant/blob/master/src/commands/BatchController.php#L512
https://github.com/schmunk42/yii2-giiant/blob/master/src/commands/BatchController.php#L532
This PR removes the first one.
=> Removed duplicate 'template' key
